### PR TITLE
Use SPDX identifiers

### PR DESCRIPTION
**Pull request by escarlson**
This PR replaces the three license text boxes with dropdowns containing a set of licenses, of which the corresponding SPDX identifier is populated in the SVG. The select2 library is also used to allow the user to filter a long list of licenses.

Currently, the licenses included for software are from the list of OSI-approved licenses according to [SPDX](https://spdx.org/licenses/). I also added a "None" option for software, to correspond with the same option on the OSHWA Certification application.
Hardware and documentation licenses included are an approximate guess based on what seems to be popular.

See in action at https://eric116.github.io/certification-mark-generator/facts

For discussion: what licenses might need to be added/removed from the three categories?

### CODE REVIEW

**Review by jywarren — COMMENTED** [review]
This looks awesome. Do you think we should "feature" some common ones near the top? And, should we show CERN OHL 1.2  as the first value as that (if i understand) would appear as the default selection?

What if, instead of removing the text `input`, we had the `select` element populate the input, so that people could insert their own licenses if they don't find what they want? I am thinking about how back in the day, Flickr, or Thingiverse didn't have all possible options and the need for flexibility, but open to discussion. 

Overall this looks awesome. many thanks. What do you think about the "select fills an input" idea before merging this?

**Comment by escarlson** [comment]
Yeah those things sound good, so I made some changes. I moved some licenses into a "Popular licenses" group at the top, and the user can now input custom text in the dropdown (select2 library made this super simple). I originally indicated the popular licenses by surrounding that section with disabled options, but in the last commit I changed it into option groups. I'm kind of on the fence about which version looks better. If the former, can just revert to 897f2e1.
If we don't want any license selected as the default, I can add in a bit to the JS to clear that.
And of course, which licenses are popular is up for discussion, I just made an informed guess.

**Comment by jywarren** [comment]
This all looks great. Ready to merge? Anyone you want to check with first? Thanks!

**Comment by escarlson** [comment]
I think it's all good!

**Comment by mwweinberg** [comment]
Sorry for being MIA on this!  I wasn't watching the repo and didn't realize that you were updating everything.

This looks really great.  I like how much flexibility it gives users while still promoting some of the most popular licenses.  The shift to using SPDX to identify licenses will also make things much easier in the future.

The only tweak I would suggest is with the suggested licenses. Can we pull CERN 1.2, Apache 2.0, and GPL v2 out of their respective recommended sections?  For the hardware I think it makes sense to push people towards the newer CERN licenses.  On the software side, I think the same is true for GPL. We also don't get as much Apache licensed stuff in the certification, so it probably makes sense to consolidate the recommendations around MIT and GPL3+.

Thank you for pulling all of this together - so exciting!

**Comment by escarlson** [comment]
Forgot about this for a bit as well. Updated with those removed from the popular licenses section.

**Comment by escarlson** [comment]
@jywarren Whenever you have a chance, I think this should be ready to merge. Thanks!

**Comment by jywarren** [comment]
Sorry! My notifications must be a little bit off! Done!!

**Pull request merged**
